function [fitresult, gof] = doubleExpFit(x, y, plotfit)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'gmean' fit:
%      X Input: x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Nov-2022 09:36:25


%% Fit: 'gmean'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
if plotfit
    figure( 'Name', 'double exponential fit' );
    h = plot( fitresult, xData, yData);
    legend( h, 'y vs. x', 'fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
    % Label axes
    xlabel( 'x', 'Interpreter', 'none' );
    ylabel( 'y', 'Interpreter', 'none' );
    grid on
end


